### PR TITLE
First Draft if Dinner recipie

### PR DESCRIPTION
**Pull request by fernandomorenopayro**
## 🎯 Objective

First draft of  Dinner Recipe instructions 

## 🛠️ Changes made

First draft

## 👥 Who needs to review this Pull Request? 

@threedom 
@smanda1a382j 
@csmith42

### CODE REVIEW

**Review by threedom — APPROVED** [review]
This looks good as a first draft for the recipe. 
I will take it from here and add my thoughts

**Review by smanda1a382j — COMMENTED** [review]
This could go great with some sour cream.

**Review by smanda1a382j — COMMENTED** [review]
Reviewed for complete steps and all necessary ingredients.  Looks good.

**Review by threedom — APPROVED** [review]
Hit's the mark of being a quick dinner recipe.
I checked ingredients, equipment, and steps to prepare.

**Review by csmith42 — APPROVED** [review]
This recipe seems complete 🙌🏼

**Pull request merged**
